version: '3.3'

volumes:
  mongo:
services:
  backend:
    image: mern-stack
    build: .
    # tty: true
    ports:
      - 8080:8080
    volumes:
      - ./node/src:/opt/mern-stack/src
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mernStack
    volumes:
      - mongo:/data/db